### PR TITLE
Issue 244

### PR DESCRIPTION
**Pull request by chearon**

### CODE REVIEW

**Comment by Bnaya** [comment]
+1 for this one!

**Comment by Bnaya** [comment]
I'm trying this great PR and i've encountered compatibility problem after build
I have handlebar helper that looks like:
```js
define(['hbs/handlebars'], function (Handlebars) {
    'use strict';

    Handlebars.registerHelper('ifCond', function (v1, operator, v2, options) {
 // some code bla bla
    });
});
```
On dev, before r.js build its works great.
In build im stubbing 'hbs/handlebars', so 'hbs/handlebars' becomes an empty object
so i get "Handlebars.registerHelper is not a function" exception.
and if i point hbs/handalbars to ->hbs/handlebars.runtime on the paths config the build fails because he needs the full lib during build.

I believe a can overcome this by adding global 'handerbars' in the paths and use it on my helpers, and point it to the runtime on build but i want to avoid it.

**Comment by chearon** [comment]
@Bnaya I had the exact issue you're describing when I was working on this PR. You had the timeout because RequireJS [does not allow you](http://requirejs.org/docs/errors.html#timeout) to call an anonymous module two different ways (last bullet point). [I tried to explain it here](https://github.com/chearon/require-handlebars-plugin/commit/445f0b6f7e954ad78626a235db9c338f15cb2a8a). So the key is to let the plugin use `hbs/handlebars`, while your helpers + the `handlebarsPath` setting use the module name `handlebars`, which you point to `hbs/handlebars.runtime` in your paths config.

I think your example would work if you pointed `handlebarsRuntime` to `vendor/hbs/handlebars.runtime` instead, and make sure `hbs.handlebarsPath` option is set to `handlebarsRuntime`.

It is a little weird but I can't think of any way to make it more simple since requireJS doesn't let you call an anonymous module two different ways.

**Comment by Bnaya** [comment]
Ok, so if i got it:
on dev mode:
the hbs/handlebars used to compile, while the handerbars.runtime used to run & register helpers
On build mode its the same, and the hbs/handlebars is stubed.
And it even working :P 

So maybe to better represent the parts of handerbars.js (which is just use to compile) and handerbars.runtime.js that should be used also in dev mode, the names should be changed.
handerbars.js should be handerbars.compiler.js

**Comment by chearon** [comment]
Yep! handlebars.compiler.js makes slightly more sense, but then it's not clear that just `handlebars.js` is only the runtime and not the full thing. I didn't want to modify the plugin too much in this PR

**Comment by Bnaya** [comment]
ping @chearon @SlexAxton  ;)

**Pull request merged**
