### PR TITLE
First pass at Upgrading handlebars/runtime to 3.0.3

### PR DESCRIPTION
**Pull request by chrisrink**
Update hbs to use new AST formats and reorganize a bit.
Update hbs to have partials meta for easy dynamic partial registration
Add dynamic partial test
Remove composeParts pieces as they were only capturing first level variables and not used in code.

This is a first pass at this and since I am new to this code it would be good to have input if I missed any cases.

### CODE REVIEW

**Comment by SlexAxton** [comment]
Looking pretty good. Most of it looks like straightforward replacements, so that's likely fine.

It looks like you're using tabs, which is fine on it's own, but mixed with the spaces that I'm using in the file, it makes the formatting very awkward. Would you mind matching that spaces here? (you can see in the diffs if it's looking good in your editor.)

Thanks for working on this!

**Comment by chrisrink** [comment]
Great!
 I'll convert my tabs to spaces today.

**Comment by chrisrink** [comment]
Changes made. Also, as this is an updated version of handlebars, it might be a good idea to bump the version number on the this plugin.

**Comment by chrisrink** [comment]
Just found some issues with the isHelper check so don't merge yet. I running a few extra tests and will update the branch once I figure it out.

**Comment by biakabuka** [comment]
When do you think it will be usable? I really need the support for subexpressions in partial calls that's in Hbs 3.0 for my project.

Need any help?

**Pull request merged**
